### ISSUE TITLE
POO

### ISSUE THREAD

**Issue by MarllonCampos** [Humildeficador/ProjetoEtec#1]
https://github.com/Humildeficador/ProjetoEtec/tree/f6b5609b9de1020076eebe7d5151ae87657aa901/produto/back-end/models
Todas as funções que tu cria aqui, poderiam estar localizadas dentro de um arquivo só, onde você poderia criar uma classe (conceito de POO-Programação Orientada a Objetos) que seus métodos(outro conceito de POO) realizariam as ações desta funções

**Comment by Humildeficador** [comment]
Valeu, quando eu terminar tudo por completo eu posso fazer dessa forma!
